mysql:
    connect: mysql:host=localhost:3306;dbname=armaki
    user: root
    pass: root
    options:
      PDO::ATTR_ERRMODE: PDO::ERRMODE_EXCEPTION
      PDO::ATTR_DEFAULT_FETCH_MODE: PDO::FETCH_NUM
log:
  channel: amarki
  file: app.log